# Generated by Django 4.0.3 on 2022-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('num_secu', models.CharField(editable=False, max_length=13, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=10)),
            ],
        ),
    ]
