# Generated by Django 4.0.3 on 2022-05-05 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_machine_mach_machine_maintenacedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenaceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 9, 24, 43, 836343)),
        ),
    ]
