# Generated by Django 4.0.3 on 2022-05-24 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0007_alter_machine_maintenacedate_alter_personnel_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenaceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 7, 55, 28, 968971)),
        ),
    ]
