# Generated by Django 2.2.25 on 2022-05-24 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0013_auto_20220524_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenaceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 10, 0, 50, 42906)),
        ),
    ]
