# Generated by Django 4.0.3 on 2022-05-30 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0014_auto_20220524_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenaceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 30, 8, 25, 51, 2263)),
        ),
    ]
